### ISSUE TITLE
Right side bar scrolling does not behave like main page

### ISSUE THREAD

**Issue by TDHTTTT** [azlen/roam-themes#23]
I am using vim-mode by roam-toolkit, although navigation on the main page works fine, it does not work in the right side bar. For example, when using "j" to move down, once it hits the bottom block, the page will not scroll. In other word, I am trying to find why the main page scrolling is different from the right side bar's.

I've been looking at this part in the css, but not able to find the reason. 
```css
/* spacing and scrolling */
#roam-right-sidebar-content > * {
    margin: 0px 0px 0 20px !important;
    overflow-x: hidden;
    /*overflow-y: auto !important;*/
    max-height: 100vh;
    padding: 50px 0px 100px 0px;
    
    /* pesky bottom border/outline in chrome won't go away! */
    /* this does not fix it */
    border: none !important;
    outline: none !important;
}

#roam-right-sidebar-content {
    visibility: visible;
    display: flex;
    flex-direction: var(--page-order);
    align-items: flex-start; /* allow pages to have their own height */
    justify-content: flex-end;
}
```
